### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims 

### ISSUE THREAD

**Issue by christian-bromann** [cncf/devstats-helm-example#6]
When trying to install this locally in my `docker desktop` cluster a variety of pods aren't starting due to `pod has unbound immediate PersistentVolumeClaims`:

```
devstats-grafana-prometheus-5b4cbbfc77-l6l8z   0/1     Running   0          83s
devstats-postgres-0                            0/1     Pending   0          83s
devstats-provision-cncf                        0/1     Pending   0          83s
devstats-provision-istio                       0/1     Pending   0          83s
devstats-provision-kubeflow                    0/1     Pending   0          83s
devstats-provision-prometheus                  0/1     Pending   0          83s
```

Any hint what might have gone wrong?

**Comment by lukaszgryglicki** [comment]
Not enough data, but each pod requires persistent volumes - Postgres pods require persistent volumes to hold database storage, projects pod need persistent storage to hold git repos clones. You need to make sure that persistent volumes are created.

**Comment by christian-bromann** [comment]
@lukaszgryglicki I was able to get it up and running by adding more PVs. However it seems that devstats isn't build for providing dashboards for non CNCF projects, is that right?

**Comment by lukaszgryglicki** [comment]
This repo is an example deployment of a few CNCF projects for a demo. To deploy your own projects you need to adjust your configuration (define own projects, etc.).

**Comment by christian-bromann** [comment]
> To deploy your own projects you need to adjust your configuration (define own projects, etc.).

Mhm 🤔 maybe I judged to early but from what I saw, e.g. the logo is being copied from https://github.com/cncf/devstats/tree/master/grafana/img which causes errors in the projects pods:

```
Patching Grafana
cp: cannot stat 'grafana/img/<my-project>.svg': No such file or directory
```

**Comment by christian-bromann** [comment]
Also it seems that `psql.sh` is not existing if the project name is arbitrary.

**Comment by lukaszgryglicki** [comment]
You need to have your project's SVG file (or specify flags to skip that) also `psql.sh `is project-specific - this is where you fetch all data for a particular project.
Again, this repo is just an example of deployment fr a few CNCF projects.
